# Generated by Django 2.2.6 on 2019-12-20 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191220_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='curso',
            field=models.CharField(blank=True, max_length=120, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='escolaridade',
            field=models.CharField(blank=True, choices=[('FI', 'Ensino Fundamental Incompleto'), ('FC', 'Ensino Fundamental Completo'), ('MI', 'Ensino Medio Incompleto'), ('MC', 'Ensino Medio Completo'), ('SUP', 'Ensino Superior Completo')], max_length=3, verbose_name='Escolaridade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=2, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='idade',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nacionalidade',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nacionalidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='perfil_especifico',
            field=models.CharField(default=models.CharField(max_length=120, verbose_name='Nome do Usuário'), editable=False, max_length=120),
        ),
    ]
