# Generated by Django 2.2.6 on 2019-12-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191220_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='curso',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='escolaridade',
            field=models.CharField(blank=True, choices=[('FI', 'Ensino Fundamental Incompleto'), ('FC', 'Ensino Fundamental Completo'), ('MI', 'Ensino Medio Incompleto'), ('MC', 'Ensino Medio Completo'), ('SUP', 'Ensino Superior Completo')], max_length=3, null=True, verbose_name='Escolaridade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=2, null=True, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nacionalidade',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nacionalidade'),
        ),
    ]
