# Generated by Django 2.2.6 on 2019-12-20 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191220_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome do Formulário')),
                ('descricao', models.CharField(blank=True, max_length=120, null=True, verbose_name='Descricao')),
                ('data_inicial', models.DateField(null=True, verbose_name='Data de Início')),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='perfil_especifico',
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome da Pergunta')),
                ('pergunta', models.CharField(max_length=120, verbose_name='Pergunta')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Formulario')),
            ],
        ),
    ]
