# Generated by Django 2.2.7 on 2020-01-05 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191220_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=120, null=True, verbose_name='Texto da alternativa')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resp', models.CharField(max_length=120, null=True, verbose_name='Resposta')),
                ('pub_data', models.DateTimeField(null='True', verbose_name='Data da resposta')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome do Usuário')),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('genero', models.CharField(blank=True, choices=[('Masc', 'Masculino'), ('Femin', 'Feminino'), ('Outro', 'Outro')], max_length=2, null=True, verbose_name='Gênero')),
                ('escolaridade', models.CharField(blank=True, choices=[('FI', 'Ensino Fundamental Incompleto'), ('FC', 'Ensino Fundamental Completo'), ('MI', 'Ensino Medio Incompleto'), ('MC', 'Ensino Medio Completo'), ('SUP', 'Ensino Superior Completo')], max_length=3, null=True, verbose_name='Escolaridade')),
                ('curso', models.CharField(blank=True, max_length=120, null=True, verbose_name='Curso')),
                ('nacionalidade', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nacionalidade')),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='key',
        ),
        migrations.AlterField(
            model_name='formulario',
            name='nome',
            field=models.CharField(max_length=120, verbose_name='Nome do formulário'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='nome',
            field=models.CharField(max_length=120, verbose_name='Nome da pergunta'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='form_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Formulario'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='resp_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Usuario'),
        ),
        migrations.AddField(
            model_name='alternativa',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Pergunta'),
        ),
    ]
