# Generated by Django 2.2.7 on 2020-01-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200105_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='data_final',
            field=models.DateField(null=True, verbose_name='Data Final'),
        ),
    ]
