# Generated by Django 2.2.6 on 2020-01-09 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_formulario_data_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.AddField(
            model_name='formulario',
            name='perguntas',
            field=models.ManyToManyField(blank=True, to='blog.Pergunta'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('Masc', 'Masculino'), ('Femin', 'Feminino'), ('Outro', 'Outro')], max_length=15, null=True, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=120, null=True, verbose_name='Nome do Usuário'),
        ),
    ]
