# Generated by Django 2.2.6 on 2020-01-09 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200109_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='perfil_especifico',
            field=models.ForeignKey(default=1, max_length=120, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.PerfilGeral'),
            preserve_default=False,
        ),
    ]
