# Generated by Django 2.2.6 on 2020-01-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200109_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilgeral',
            name='formularios',
            field=models.ManyToManyField(blank=True, to='blog.Formulario'),
        ),
    ]
