# Generated by Django 2.2.7 on 2020-01-16 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_perfilgeral_formularios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='form_key',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='resp',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='resp_key',
        ),
        migrations.AddField(
            model_name='resposta',
            name='alternativa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Alternativa'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='formulario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Formulario'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='pergunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Pergunta'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='formularios',
            field=models.ManyToManyField(blank=True, to='blog.Formulario'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='pub_data',
            field=models.DateField(blank=True, null=True, verbose_name='Data da resposta'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='curso',
            field=models.CharField(max_length=120, null=True, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='escolaridade',
            field=models.CharField(choices=[('FI', 'Ensino Fundamental Incompleto'), ('FC', 'Ensino Fundamental Completo'), ('MI', 'Ensino Medio Incompleto'), ('MC', 'Ensino Medio Completo'), ('SI', 'Ensino Superior Incompleto'), ('SC', 'Ensino Superior Completo')], max_length=3, null=True, verbose_name='Escolaridade'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('Masc', 'Masculino'), ('Femin', 'Feminino'), ('Outro', 'Outro')], max_length=15, null=True, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idade',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nacionalidade',
            field=models.CharField(max_length=120, null=True, verbose_name='Nacionalidade'),
        ),
    ]
