# Generated by Django 3.0.2 on 2020-01-24 19:12

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200124_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tela',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='tela',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Tela'),
        ),
        migrations.AlterField(
            model_name='escolha',
            name='tela',
            field=models.ForeignKey(blank=True, limit_choices_to=blog.models.limitar_tela_filha, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Tela'),
        ),
    ]
