# Generated by Django 3.0.2 on 2020-01-25 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200124_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='tela',
            name='ultimo',
            field=models.BooleanField(default=False, verbose_name='É um teste'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='arvores',
            field=models.ManyToManyField(blank=True, editable=False, to='blog.Arvore'),
        ),
        migrations.AlterField(
            model_name='escolha',
            name='tela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Tela'),
        ),
    ]
