# Generated by Django 3.0.2 on 2020-01-25 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200125_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tela',
        ),
        migrations.AddField(
            model_name='tela',
            name='question',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Question'),
        ),
    ]
